export default {
  login: "louiestokk",
  id: 76744837,
  node_id: "MDQ6VXNlcjc2NzQ0ODM3",
  avatar_url: "https://avatars.githubusercontent.com/u/76744837?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/louiestokk",
  html_url: "https://github.com/louiestokk",
  followers_url: "https://api.github.com/users/louiestokk/followers",
  following_url:
    "https://api.github.com/users/louiestokk/following{/other_user}",
  gists_url: "https://api.github.com/users/louiestokk/gists{/gist_id}",
  starred_url: "https://api.github.com/users/louiestokk/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/louiestokk/subscriptions",
  organizations_url: "https://api.github.com/users/louiestokk/orgs",
  repos_url: "https://api.github.com/users/louiestokk/repos",
  events_url: "https://api.github.com/users/louiestokk/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/louiestokk/received_events",
  type: "User",
  site_admin: false,
  name: "Louie Stokk",
  company: "Stihl ",
  blog: "louiestokk@gmail.com",
  location: "Sweden",
  email: null,
  hireable: null,
  bio: "Front-end developer\r\nJavascript / React",
  twitter_username: null,
  public_repos: 36,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-12-29T16:56:44Z",
  updated_at: "2022-01-14T23:47:13Z",
};
